import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { RenderedMarkdown } from '../packages/contracts';
import { english } from '../packages/i18n';
import { fixture } from './helpers';

test('unsaved previews reuse Markdown resolution without changing drafts, Git or publication', async t => {
  const f = await fixture(); t.after(f.cleanup);
  await fs.mkdir(path.join(f.config.contentDir, '_images'));
  await fs.writeFile(path.join(f.config.contentDir, '_images', 'art.png'), 'preview image');
  f.config.site.basePath = '/knowledge';
  const admin = await f.start('admin'); const reader = await f.start('public');
  const wiki = admin.service.wiki!;
  const before = JSON.stringify(wiki.pages);
  const head = await wiki.repository.head();
  const publication = await fs.readFile(path.join(f.config.contentDir, '.wiki', 'publication.json'), 'utf8');
  const input = { path: 'guides/new.md', content: '# Unsaved\n\n[[first#A section|First]]\n\n![[art.png|200]]\n\n## New heading\n[[#New heading]]\n<script>alert(1)</script>\n' };
  const response = await admin.request('/knowledge/api/admin/preview', 'POST', input);
  assert.equal(response.status, 200);
  const rendered = await response.json() as RenderedMarkdown;
  assert.equal(rendered.title, 'Unsaved');
  assert.match(rendered.html, /data-page-path="guides\/first.md"/);
  assert.match(rendered.html, /data-page-suffix="#a-section"/);
  assert.match(rendered.html, /data-page-suffix="#new-heading"/);
  assert.match(rendered.html, /src="\/knowledge\/media\/_images\/art.png"/);
  assert.match(rendered.html, /&lt;script&gt;/); assert.doesNotMatch(rendered.html, /<script>/);
  assert.equal(JSON.stringify(wiki.pages), before);
  assert.equal(await wiki.repository.head(), head);
  assert.equal(await fs.readFile(path.join(f.config.contentDir, '.wiki', 'publication.json'), 'utf8'), publication);
  assert.equal((await reader.request('/knowledge/api/page?path=guides/new.md')).status, 404);
  assert.equal((await reader.request('/knowledge/api/admin/preview', 'POST', input)).status, 404);
  const unnamed = await (await admin.request('/knowledge/api/admin/preview', 'POST', { content: 'A new note.' })).json() as RenderedMarkdown;
  assert.equal(unnamed.title, english['editor.new']);
  assert.equal((await admin.request('/knowledge/api/admin/preview', 'POST', { path: '../escape.md', content: '' })).status, 400);
  assert.equal((await admin.request('/knowledge/api/admin/preview', 'POST', { content: 'x'.repeat(f.config.site.maxPageBytes + 1) })).status, 413);
  assert.equal((await fetch(admin.url + '/knowledge/api/admin/preview', { method: 'POST', headers: { origin: admin.url, 'content-type': 'application/json' }, body: JSON.stringify(input) })).status, 403);
});
