import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { PendingPublication, Publication } from '../packages/contracts';
import { Publisher, publicationPath } from '../apps/server/src/services/publication';
import { fixture } from './helpers';

test('batch publication reviews only pending pages and renders once for a large collection', async t => {
  const f = await fixture({ publishInitial: false }); t.after(f.cleanup);
  await fs.mkdir(path.join(f.config.contentDir, 'collection'));
  await Promise.all(Array.from({ length: 120 }, (_, index) => fs.writeFile(path.join(f.config.contentDir, 'collection', `${index}.md`), `# Page ${index}`)));
  const admin = await f.start('admin'); const reader = await f.start('public'); const wiki = admin.service.wiki!;
  const initial = wiki.pendingPublications();
  assert.equal(initial.length, 122);
  const render = t.mock.method(Publisher.prototype, 'render');
  assert.deepEqual(await wiki.publishBatch({ pages: initial }), { count: 122 });
  assert.equal(render.mock.callCount(), 2);
  assert.equal(wiki.pendingPublications().length, 0);
  const home = wiki.pages.find(page => page.path === 'home.md')!;
  await wiki.save(home.id, { revision: home.revision, content: '# Updated home\n\n[[New]]' });
  const created = await wiki.create({ path: 'collection/New.md', content: '# New\n\n[[home]]' });
  const reviewed = await (await admin.request('/api/admin/publication/pending')).json() as PendingPublication[];
  assert.equal(reviewed.length, 2);
  assert.deepEqual(new Set(reviewed.map(page => page.status)), new Set(['draft', 'changes']));
  assert.equal(JSON.stringify(reviewed).includes('Updated home'), false);
  const later = await wiki.create({ path: 'Later.md', content: '# Not reviewed' });
  const gitHead = await wiki.repository.head();
  const callsBefore = render.mock.callCount();
  const result = await admin.request('/api/admin/publication/publish', 'POST', { pages: reviewed });
  assert.equal(result.status, 200);
  assert.deepEqual(await result.json(), { count: 2 });
  assert.equal(render.mock.callCount() - callsBefore, 2);
  assert.equal(await wiki.repository.head(), gitHead);
  assert.deepEqual(wiki.pendingPublications().map(page => page.id), [later.page.id]);
  const publicHome = await (await reader.request('/api/page')).json();
  assert.equal(publicHome.title, 'Updated home');
  assert.match(publicHome.html, /data-page-path="collection\/New.md"/);
  assert.equal((await reader.request('/api/page?path=collection%2FNew.md')).status, 200);
  assert.equal((await reader.request('/api/page?path=Later.md')).status, 404);
  const snapshotBefore = await fs.readFile(publicationPath(f.config.contentDir), 'utf8');
  assert.deepEqual(await wiki.publishBatch({ pages: reviewed }), { count: 0 });
  assert.equal(await fs.readFile(publicationPath(f.config.contentDir), 'utf8'), snapshotBefore);
  assert.equal(wiki.get(created.page.id).revision, created.page.revision);
  assert.equal((await reader.request('/api/admin/publication/pending')).status, 404);
  assert.equal((await reader.request('/api/admin/publication/publish', 'POST', { pages: reviewed })).status, 404);
  assert.equal((await fetch(admin.url + '/api/admin/publication/publish', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ pages: reviewed }) })).status, 403);
});

test('batch publication rejects stale or deleted reviews without publishing any page', async t => {
  const f = await fixture(); t.after(f.cleanup);
  const admin = await f.start('admin'); const wiki = admin.service.wiki!;
  const first = await wiki.create({ path: 'First.md', content: '# First' });
  const second = await wiki.create({ path: 'Second.md', content: '# Second' });
  const reviewed = wiki.pendingPublications();
  await wiki.save(second.page.id, { revision: second.page.revision, content: '# A later change' });
  const before = await fs.readFile(publicationPath(f.config.contentDir), 'utf8');
  const response = await admin.request('/api/admin/publication/publish', 'POST', { pages: reviewed });
  assert.equal(response.status, 409);
  assert.equal((await response.json()).error.code, 'error.publishBatchChanged');
  assert.equal(await fs.readFile(publicationPath(f.config.contentDir), 'utf8'), before);
  const nextReview = wiki.pendingPublications();
  await wiki.delete(second.page.id, { revision: wiki.get(second.page.id).revision });
  await assert.rejects(wiki.publishBatch({ pages: nextReview }), /error.publishBatchChanged/);
  await assert.rejects(wiki.publishBatch({ pages: [nextReview[0]!, nextReview[0]!] }), /error.invalidRequest/);
  assert.equal((await admin.request('/api/admin/publication/publish', 'POST', { pages: [] })).status, 400);
  const snapshot = JSON.parse(await fs.readFile(publicationPath(f.config.contentDir), 'utf8')) as Publication;
  assert.equal(snapshot.pages.some(page => page.id === first.page.id), false);
});

test('a batch rejects public path collisions before replacing its durable publication state', async t => {
  const f = await fixture(); t.after(f.cleanup);
  const admin = await f.start('admin'); const wiki = admin.service.wiki!;
  const original = wiki.pages.find(page => page.path === 'guides/first.md')!;
  await wiki.move(original.id, { path: 'guides/renamed.md', revision: original.revision });
  const replacement = await wiki.create({ path: 'guides/first.md', content: '# Replacement' });
  const before = await fs.readFile(publicationPath(f.config.contentDir), 'utf8');
  await assert.rejects(wiki.publishBatch({ pages: [{ id: replacement.page.id, revision: replacement.page.revision }] }), /error.publishedPath/);
  assert.equal(await fs.readFile(publicationPath(f.config.contentDir), 'utf8'), before);
  assert.deepEqual(await wiki.publishBatch({ pages: wiki.pendingPublications() }), { count: 2 });
  await admin.service.close();
  const restarted = await f.start('admin');
  assert.deepEqual(restarted.service.wiki!.pendingPublications(), []);
});
